/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadulp.Vistas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import universidadulp.AccesoADatos.AlumnoData;
import universidadulp.AccesoADatos.Conexion;
import universidadulp.AccesoADatos.InscripcionData;
import universidadulp.Entidades.Alumno;
import universidadulp.Entidades.Inscripcion;

/**
 *
 * @author jero
 */
public class Inscripciones extends javax.swing.JInternalFrame {
    Connection con =Conexion.getConnection();
    /**
     * Creates new form Inscripciones
     */
    public Inscripciones() {
        initComponents();
        mostrarComboBox();
        mostrarTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcmatNoinscriptas = new javax.swing.JCheckBox();
        jcmatinscriptas = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaInscripcion = new javax.swing.JTable();
        jcbListaAlumnosInscripcion = new javax.swing.JComboBox<>();
        jbanular = new javax.swing.JButton();
        jtsalir = new javax.swing.JButton();
        jbinscribir = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setText("Formulario de inscripcion");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setForeground(java.awt.Color.black);
        jLabel5.setText("Seleccione un alumno:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setText("Listado de materias");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setText("Materias inscriptas");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setForeground(java.awt.Color.black);
        jLabel8.setText("Materias no inscriptas");

        jcmatNoinscriptas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcmatNoinscriptas.setForeground(java.awt.Color.black);

        jcmatinscriptas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcmatinscriptas.setForeground(java.awt.Color.black);

        jTablaInscripcion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTablaInscripcion.setForeground(java.awt.Color.black);
        jTablaInscripcion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Año"
            }
        ));
        jScrollPane1.setViewportView(jTablaInscripcion);

        jcbListaAlumnosInscripcion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbListaAlumnosInscripcion.setForeground(java.awt.Color.black);
        jcbListaAlumnosInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbListaAlumnosInscripcionActionPerformed(evt);
            }
        });

        jbanular.setText("Anular inscripcion");

        jtsalir.setText("Salir");
        jtsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtsalirActionPerformed(evt);
            }
        });

        jbinscribir.setText("inscribir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jcbListaAlumnosInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcmatinscriptas)
                                .addGap(2, 2, 2)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcmatNoinscriptas)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel8)))))
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbinscribir)
                        .addGap(71, 71, 71)
                        .addComponent(jbanular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtsalir)
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbListaAlumnosInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcmatinscriptas)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel8))
                            .addComponent(jcmatNoinscriptas)
                            .addComponent(jLabel7))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbanular)
                    .addComponent(jtsalir)
                    .addComponent(jbinscribir))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbListaAlumnosInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbListaAlumnosInscripcionActionPerformed
       mostrarComboBox();
    }//GEN-LAST:event_jcbListaAlumnosInscripcionActionPerformed

    private void jtsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtsalirActionPerformed
    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jtsalirActionPerformed
      public void mostrarComboBox() {
        try {
            String sql="SELECT idAlumno , apellido, nombre FROM alumno";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
            int idAl =rs.getInt("idAlumno");
            String apellido =rs.getString("apellido");
            String nombre =rs.getString("nombre");
            String datos = idAl +" "+apellido+" "+nombre;
            jcbListaAlumnosInscripcion.addItem(datos);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "error en el sql ");
        }
    }
    
        public void mostrarTabla() {
         try{
  DefaultTableModel modelo =new DefaultTableModel();
  jTablaInscripcion.setModel(modelo);
  PreparedStatement ps =null;
  ResultSet rs=null;
  Connection con =Conexion.getConnection();
  
  String sql ="SELECT a.idalumno, a.apellido, m.anio AS anio_que_cursa\n" +
"FROM alumno a\n" +
"CROSS JOIN (SELECT DISTINCT anio FROM materia) m;";
  ps =con.prepareStatement(sql);
  rs =ps.executeQuery();
  ResultSetMetaData rsMd =rs.getMetaData();
  int cantidadColumnas =rsMd.getColumnCount();
  modelo.addColumn("IdAlumno");
  modelo.addColumn("NOMBRE_Alumno");
  modelo.addColumn("NOTA");
  while(rs.next()){
Object []filas =new Object[cantidadColumnas];
for(int i =0;i<cantidadColumnas;i++){
filas[i]=rs.getObject(i+1);
}
modelo.addRow(filas);
  
  }
          
          
 }catch(SQLException e){
 JOptionPane.showMessageDialog(null,"Error al cargar tabla de datos");
 }
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaInscripcion;
    private javax.swing.JButton jbanular;
    private javax.swing.JButton jbinscribir;
    private javax.swing.JComboBox<String> jcbListaAlumnosInscripcion;
    private javax.swing.JCheckBox jcmatNoinscriptas;
    private javax.swing.JCheckBox jcmatinscriptas;
    private javax.swing.JButton jtsalir;
    // End of variables declaration//GEN-END:variables
}
