/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadulp.Vistas;

/**
 *
 * @author jero
 */
public class Administracion extends javax.swing.JPanel {

    /**
     * Creates new form Administracion
     */
    public Administracion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelInscripciones = new javax.swing.JPanel();
        panelTop1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelMid1 = new javax.swing.JPanel();
        panelTopHalf1 = new javax.swing.JPanel();
        panelCB = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        panelSeleccion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        panelPalabra = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        panelTopHalf2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelBot1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panelNotas = new javax.swing.JPanel();
        panelTop2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelMid2 = new javax.swing.JPanel();
        panelMidSeleccion = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        panelMidTable = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        panelBot2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        panelAlumnos = new javax.swing.JPanel();
        paelTop3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panelMid3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        panelBot3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelInscripciones.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(21, 39, 43)));
        panelInscripciones.setPreferredSize(new java.awt.Dimension(428, 0));
        panelInscripciones.setLayout(new java.awt.BorderLayout());

        panelTop1.setPreferredSize(new java.awt.Dimension(0, 60));
        panelTop1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulario inscripcion");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(21, 39, 43)));
        panelTop1.add(jLabel1, java.awt.BorderLayout.CENTER);

        panelInscripciones.add(panelTop1, java.awt.BorderLayout.NORTH);

        panelMid1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(21, 39, 43)));
        panelMid1.setLayout(new java.awt.BorderLayout());

        panelTopHalf1.setPreferredSize(new java.awt.Dimension(100, 240));
        panelTopHalf1.setLayout(new java.awt.BorderLayout());

        panelCB.setPreferredSize(new java.awt.Dimension(0, 80));
        panelCB.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Seleccione un alumno:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        panelCB.add(jLabel2, gridBagConstraints);

        jComboBox1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jComboBox1.setForeground(java.awt.Color.white);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(180, 40));
        panelCB.add(jComboBox1, new java.awt.GridBagConstraints());

        panelTopHalf1.add(panelCB, java.awt.BorderLayout.NORTH);

        panelSeleccion.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Materias inscriptas");
        panelSeleccion.add(jLabel3, new java.awt.GridBagConstraints());

        jCheckBox1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jCheckBox1.setForeground(java.awt.Color.white);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 14);
        panelSeleccion.add(jCheckBox1, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Materias no inscriptas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        panelSeleccion.add(jLabel4, gridBagConstraints);

        jCheckBox2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jCheckBox2.setForeground(java.awt.Color.white);
        panelSeleccion.add(jCheckBox2, new java.awt.GridBagConstraints());

        panelTopHalf1.add(panelSeleccion, java.awt.BorderLayout.CENTER);

        panelPalabra.setPreferredSize(new java.awt.Dimension(428, 80));
        panelPalabra.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Listado de materias");
        panelPalabra.add(jLabel8, java.awt.BorderLayout.CENTER);

        panelTopHalf1.add(panelPalabra, java.awt.BorderLayout.SOUTH);

        panelMid1.add(panelTopHalf1, java.awt.BorderLayout.NORTH);

        panelTopHalf2.setPreferredSize(new java.awt.Dimension(428, 340));
        panelTopHalf2.setLayout(new java.awt.BorderLayout());

        jTable1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTable1.setForeground(java.awt.Color.white);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        panelTopHalf2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelMid1.add(panelTopHalf2, java.awt.BorderLayout.CENTER);

        panelInscripciones.add(panelMid1, java.awt.BorderLayout.CENTER);

        panelBot1.setPreferredSize(new java.awt.Dimension(428, 80));
        panelBot1.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setForeground(java.awt.Color.white);
        jButton1.setText("Anular inscripcion");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(21, 39, 43)));
        panelBot1.add(jButton1);

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setForeground(java.awt.Color.white);
        jButton2.setText("Inscribir");
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(21, 39, 43)));
        panelBot1.add(jButton2);

        panelInscripciones.add(panelBot1, java.awt.BorderLayout.SOUTH);

        add(panelInscripciones, java.awt.BorderLayout.WEST);

        panelNotas.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(21, 39, 43)));
        panelNotas.setPreferredSize(new java.awt.Dimension(426, 0));
        panelNotas.setLayout(new java.awt.BorderLayout());

        panelTop2.setPreferredSize(new java.awt.Dimension(0, 60));
        panelTop2.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Carga de notas");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(21, 39, 43)));
        panelTop2.add(jLabel5, java.awt.BorderLayout.CENTER);

        panelNotas.add(panelTop2, java.awt.BorderLayout.NORTH);

        panelMid2.setLayout(new java.awt.BorderLayout());

        panelMidSeleccion.setPreferredSize(new java.awt.Dimension(0, 80));
        panelMidSeleccion.setLayout(new java.awt.GridBagLayout());

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Seleccione un alumno:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        panelMidSeleccion.add(jLabel6, gridBagConstraints);

        jComboBox2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jComboBox2.setForeground(java.awt.Color.white);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setPreferredSize(new java.awt.Dimension(170, 40));
        panelMidSeleccion.add(jComboBox2, new java.awt.GridBagConstraints());

        panelMid2.add(panelMidSeleccion, java.awt.BorderLayout.NORTH);

        panelMidTable.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(21, 39, 43)));
        panelMidTable.setPreferredSize(new java.awt.Dimension(0, 500));
        panelMidTable.setLayout(new java.awt.BorderLayout());

        jTable2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTable2.setForeground(java.awt.Color.white);
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        panelMidTable.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        panelMid2.add(panelMidTable, java.awt.BorderLayout.SOUTH);

        panelNotas.add(panelMid2, java.awt.BorderLayout.CENTER);

        panelBot2.setPreferredSize(new java.awt.Dimension(0, 80));
        panelBot2.setLayout(new java.awt.BorderLayout());

        jButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton3.setForeground(java.awt.Color.white);
        jButton3.setText("Guardar");
        jButton3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(21, 39, 43)));
        panelBot2.add(jButton3, java.awt.BorderLayout.CENTER);

        panelNotas.add(panelBot2, java.awt.BorderLayout.SOUTH);

        add(panelNotas, java.awt.BorderLayout.CENTER);

        panelAlumnos.setPreferredSize(new java.awt.Dimension(426, 0));
        panelAlumnos.setLayout(new java.awt.BorderLayout());

        paelTop3.setPreferredSize(new java.awt.Dimension(0, 60));
        paelTop3.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Alta de alumnos");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(21, 39, 43)));
        paelTop3.add(jLabel7, java.awt.BorderLayout.CENTER);

        panelAlumnos.add(paelTop3, java.awt.BorderLayout.NORTH);

        panelMid3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(21, 39, 43)));
        panelMid3.setPreferredSize(new java.awt.Dimension(0, 100));
        panelMid3.setLayout(new java.awt.BorderLayout());

        jTable3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTable3.setForeground(java.awt.Color.white);
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        panelMid3.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        panelAlumnos.add(panelMid3, java.awt.BorderLayout.CENTER);

        panelBot3.setPreferredSize(new java.awt.Dimension(0, 80));
        panelBot3.setLayout(new java.awt.GridLayout());

        jButton4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton4.setForeground(java.awt.Color.white);
        jButton4.setText("Baja");
        jButton4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(21, 39, 43)));
        panelBot3.add(jButton4);

        jButton5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton5.setForeground(java.awt.Color.white);
        jButton5.setText("Alta");
        jButton5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(21, 39, 43)));
        panelBot3.add(jButton5);

        panelAlumnos.add(panelBot3, java.awt.BorderLayout.SOUTH);

        add(panelAlumnos, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JPanel paelTop3;
    private javax.swing.JPanel panelAlumnos;
    private javax.swing.JPanel panelBot1;
    private javax.swing.JPanel panelBot2;
    private javax.swing.JPanel panelBot3;
    private javax.swing.JPanel panelCB;
    private javax.swing.JPanel panelInscripciones;
    private javax.swing.JPanel panelMid1;
    private javax.swing.JPanel panelMid2;
    private javax.swing.JPanel panelMid3;
    private javax.swing.JPanel panelMidSeleccion;
    private javax.swing.JPanel panelMidTable;
    private javax.swing.JPanel panelNotas;
    private javax.swing.JPanel panelPalabra;
    private javax.swing.JPanel panelSeleccion;
    private javax.swing.JPanel panelTop1;
    private javax.swing.JPanel panelTop2;
    private javax.swing.JPanel panelTopHalf1;
    private javax.swing.JPanel panelTopHalf2;
    // End of variables declaration//GEN-END:variables
}
